### ISSUE TITLE
demo/page.html Store List

### ISSUE THREAD

**Issue by CurtisB123** [sapphire-bt/mcdonalds-uk-survey-codes#5]
When opwning demo/page.html im unable to pick a store from the list

![image](https://github.com/sapphire-bt/mcdonalds-uk-survey-codes/assets/117991968/1f614764-248f-4842-ab5c-70c9c23c5784)

**Comment by sapphire-bt** [comment]
I suspect this is because your browser is preventing the demo from reading the local file containing the list of stores.

I've just updated the demo - download it and try again; it should work now.
