### ISSUE TITLE
Demo/page.html Entry Code 

### ISSUE THREAD

**Issue by FabS23U** [sapphire-bt/mcdonalds-uk-survey-codes#6]
Just trying to use the basic generator when downloading the files and when everything is filled in I can't seem to generate an entry code 

![Screenshot_20240512_180902_Chrome](https://github.com/sapphire-bt/mcdonalds-uk-survey-codes/assets/169607534/dd26a4bf-c1da-493e-a0e6-b2735e64970b)

**Comment by sapphire-bt** [comment]
Hi there. I've not tested the demo page on mobile devices but it should work properly on desktop computers/laptops etc.

Alternatively there's a version hosted on JSFiddle (but again not tested on mobile): https://jsfiddle.net/ug29acn8/
