### ISSUE TITLE
Confirmation

### ISSUE THREAD

**Issue by irrelevantdotcom** [sapphire-bt/mcdonalds-uk-survey-codes#7]
Not really an issue with this code, but thought I'd mention.. I just had an IIS error from mcd's website. Full debug log, including:

`[Exception: Failed to execute SqlCommand:<br/>
dbo.WSE_CouponNum_Decoded_get_04 '3','A1','A1','7,2|4,7|6,5|9,11|C,0|3,14|M,1|W,3|D,4|N,6|R,8|H,9|F,10|Z,12|X,15|K,16|Q,17|G,18|V,19|P,20|B,21|T,22|J,23|Y,24|L,13']`

Nice of them to give out the decryption key.. 

My host of script is at www.irrelevant.com/mcd if anybody needs it.

**Comment by sapphire-bt** [comment]
Nice find! How did you get the error to appear? I wonder if there's any other information we could glean.

**Comment by irrelevantdotcom** [comment]
I didn't do anything special, just entered the invite code, waited ages, then got the error screen. It was mostly timeout messages, but that bit stood out. I should have saved all of it, I guess..

**Comment by sapphire-bt** [comment]
Interesting - maybe they were having some kind of server/database issue. Thanks for sharing anyway!

Feel free to reopen this if you see anything else.
