### ISSUE TITLE
Order ID?

### ISSUE THREAD

**Issue by RamenSoomi** [sapphire-bt/mcdonalds-uk-survey-codes#9]
I’m a bit confused as to where exactly I find the Order ID / where to get the order ID from. And is it possible to get it from an online receipt that McDonalds emails to you? Thanks!

**Comment by Tapwatero** [comment]
You find it on the recipet, its the first 3 characters of the survey-code (encoded in base 26)

**Comment by sapphire-bt** [comment]
@RamenSoomi 
> I’m a bit confused as to where exactly I find the Order ID / where to get the order ID from.

If it's a paper receipt, take a look at this repo's readme file (the order ID is the very first thing at the top of the receipt).

> And is it possible to get it from an online receipt that McDonalds emails to you? Thanks!

I've never ordered online so can't say. Feel free to share the receipt here.

@Tapwatero 
> You find it on the recipet, its the first 3 characters of the survey-code (encoded in base 26)

Are you talking about the paper receipts? If so, the order ID is characters 5-6; the first three are the store ID.

**Comment by Tapwatero** [comment]
My bad, confused the store Id with the order Id.
